### ISSUE TITLE
Error using CreateItem on subfolders

### ISSUE THREAD

**Issue by srkv03** [jamesiarmes/php-ews#260]
I have the following code

    //exchange server credentials
    $ews = new ExchangeWebServices($host, $username, $password);

    //Set the correct folder
    $request = new EWSType_FindFolderType();
    $request->Traversal = EWSType_FolderQueryTraversalType::DEEP;
    $request->FolderShape = new EWSType_FolderResponseShapeType();

    $request->FolderShape->BaseShape = EWSType_DefaultShapeNamesType::ALL_PROPERTIES;

    $request->IndexedPageFolderView = new EWSType_IndexedPageViewType();
    $request->IndexedPageFolderView->BasePoint = 'Beginning';
    $request->IndexedPageFolderView->Offset = 0;

    $request->ParentFolderIds = new EWSType_NonEmptyArrayOfBaseFolderIdsType();
    $request->ParentFolderIds->DistinguishedFolderId = new EWSType_DistinguishedFolderIdType();
    $request->ParentFolderIds->DistinguishedFolderId->Id = EWSType_DistinguishedFolderIdNameType::MESSAGE_FOLDER_ROOT;

    $response = $ews->FindFolder($request);

    if($response->ResponseMessages->FindFolderResponseMessage->RootFolder->TotalItemsInView > 0)
    {
        $folders = $response->ResponseMessages->FindFolderResponseMessage->RootFolder->Folders->CalendarFolder;

        foreach($folders as $folder) 
        {
            $calname = $folder->DisplayName;
            if($calname == "Training Room")
            {
                // Start building the request.
                $request = new EWSType_CreateItemType();
                $request->Items = new EWSType_NonEmptyArrayOfAllItemsType();
                $request->Items->CalendarItem = new EWSType_CalendarItemType();
                
                // Set the subject.
                $request->Items->CalendarItem->Subject = $name.": ".$subject;

                // Set the start and end times. For Exchange 2007, you need to include the timezone offset.
                // For Exchange 2010, you should set the StartTimeZone and EndTimeZone properties.
                $dateTimeArg = $y."-".$sMonth."-".$sDay." ".$sTime.":00";
                $sdate = new DateTime($dateTimeArg);
                $edate = new DateTime($dateTimeArg);

                    $request->Items->CalendarItem->Start = $sdate->format('c');
                    $edate->modify('+'.$sLength.' minutes');
                    echo "<br />";
                    $request->Items->CalendarItem->End = $edate->format('c');

                    // Set reminders
                    $request->Items->CalendarItem->ReminderIsSet = false;

                    // Or use this to specify when reminder is displayed (if this is not set, the default is 15 minutes)
                    $request->Items->CalendarItem->ReminderMinutesBeforeStart = 15;

                    // Build the body.
                    $request->Items->CalendarItem->Body = new EWSType_BodyType();
                    $request->Items->CalendarItem->Body->BodyType = EWSType_BodyTypeType::HTML;
                    $request->Items->CalendarItem->Body->_ = 'This is <b>the</b> body';

                    // Set the item class type (not required).
                    $request->Items->CalendarItem->ItemClass = new EWSType_ItemClassType();
                    $request->Items->CalendarItem->ItemClass->_ = EWSType_ItemClassType::APPOINTMENT;

                    // Set the sensitivity of the event (defaults to normal).
                    $request->Items->CalendarItem->Sensitivity = new EWSType_SensitivityChoicesType();
                    $request->Items->CalendarItem->Sensitivity->_ = EWSType_SensitivityChoicesType::NORMAL;

                    // Set the importance of the event.
                    $request->Items->CalendarItem->Importance = new EWSType_ImportanceChoicesType();
                    $request->Items->CalendarItem->Importance->_ = EWSType_ImportanceChoicesType::NORMAL;

                    // Don't send meeting invitations.
                    $request->SendMeetingInvitations = EWSType_CalendarItemCreateOrDeleteOperationType::SEND_ONLY_TO_ALL;
                    
                    $trainId = "AAAeAG5vLnJlcGx5QGRyaWxsaW5nc3lzdGVtcy5jby51awAuAAAAAAClUW7ZhfB9SLv8FjUJf49TAQAAcMMSB5K7TrQvYZIZQ8scAAAAiZfGAAA=";
                    $request->SavedItemFolderId = new EWSType_TargetFolderIdType();
                    $request->SavedItemFolderId->DistinguishedFolderId = new EWSType_DistinguishedFolderIdType();
                    $request->SavedItemFolderId->DistinguishedFolderId->Id = "CALENDAR";
                    
                    $request->SavedItemFolderId->FolderId = new EWSType_FolderIdType();
                    $request->SavedItemFolderId->FolderId = $trainId;
                    
                    $response = $ews->CreateItem($request);

The code executes well up until it creates the request, something going wrong there. I can say it does go into the loop which says "Training Room". Can someone help with this, please.

**Comment by srkv03** [comment]
The following is the error I get when I try to run the program.

Fatal error: Uncaught SoapFault exception: [a:ErrorSchemaValidation] The request failed schema validation: The required attribute 'Id' is missing. in C:\Book Rooms\Training\php\php-ews\ExchangeWebServices.php:293 Stack trace: #0 C:\Book Rooms\Training\php\php-ews\ExchangeWebServices.php(293): SoapClient->__call('CreateItem', Array) #1 C:\Book Rooms\Training\php\php-ews\ExchangeWebServices.php(293): NTLMSoapClient_Exchange->CreateItem(Object(EWSType_CreateItemType)) #2 C:\Book Rooms\Training\php\book_event.php(241): ExchangeWebServices->CreateItem(Object(EWSType_CreateItemType)) #3 {main} thrown in C:\Book Rooms\Training\php\php-ews\ExchangeWebServices.php on line 293

**Comment by srkv03** [comment]
Got it working. I changed the ItemClassType from IPM.Appointment to IPF.Appointment. Put it back to how it was originally and it worked. Dont know what the difference is between them but hey ho it worked.
