### ISSUE TITLE
GetStreamingEventsType  -no XML document 

### ISSUE THREAD

**Issue by ZaeemFarooqui** [jamesiarmes/php-ews#453]
**Version:** Release 1.0.0-rc.2

**PHP version:**5.6.25

**Microsoft Exchange version:** 2013

**Description of problem:**
I am trying to sync my system with Exchange Server by Subscription to a mailbox using SubscribeType->StreamingSubscriptionRequest.
I am accessing using an account with impersonation permissions and requesting a subscription for mailbox of a resource(room) and I am able to receive a subscriptionId in response.
Now when i provide that ID(subscriptionId) to GetStreamingEventsType request and provide ConnectionTimeout value, i get an error
 

> Fatal error: Uncaught SoapFault exception: [Client] looks like we got no XML document

**request:**
**StreamingSubscriptionRequest:**
```
<?php
    $host =hostname
    $username = 'username';
    $password = password;
    $version = Client::VERSION_2013;
    $client = new CLient($host, $username, $password, $version);

    $ei = new ExchangeImpersonationType();
    $sid = new ConnectingSIDType();
    $sid->PrimarySmtpAddress = mailboxaddress';
    $ei->ConnectingSID = $sid;
    $client->setImpersonation($ei);
    $request1 = new SubscribeType();

    $eventTypes = new NonEmptyArrayOfNotificationEventTypesType();
    $eventTypes->EventType = array('CreatedEvent','DeletedEvent','ModifiedEvent','NewMailEvent','MovedEvent','CopiedEvent','FreeBusyChangedEvent');  

    $streamSubs= new StreamingSubscriptionRequest();
    $streamSubs->EventTypes = $eventTypes;
    $streamSubs->SubscribeToAllFolders = false;

    $folder_id = new NonEmptyArrayOfBaseFolderIdsType();
    $folder_id->DistinguishedFolderId = new DistinguishedFolderIdType();
    $folder_id->DistinguishedFolderId->Id = DistinguishedFolderIdNameType::CALENDAR;
    $folder_id->DistinguishedFolderId->Mailbox = new EmailAddressType();
    $folder_id->DistinguishedFolderId->Mailbox->EmailAddress =mailboxaddress;
    $streamSubs->FolderIds = $folder_id;
    $request1->StreamingSubscriptionRequest = $streamSubs;
    $response1 = $client->Subscribe($request1);
```

**response:**

```
array (size=1)
  0 => 
    object(jamesiarmes\PhpEws\Response\SubscribeResponseMessageType)[16]
      public 'SubscriptionId' => string 'CwBidm0udGFkLmNvbRAAAABLHkD3ediITJa8mWPdboYwN4fcJmzO1Ag=' (length=56)
      public 'Watermark' => null
      public 'DescriptiveLinkKey' => null
      public 'MessageText' => null
      public 'MessageXml' => null
      public 'ResponseClass' => string 'Success' (length=7)
      public 'ResponseCode' => string 'NoError' (length=7)
```
**request:**
**GetStreamingEventsType:**
```
    $subs_ids = new NonEmptyArrayOfSubscriptionIdsType();
    $subs_ids->SubscriptionId = $response1->ResponseMessages->SubscribeResponseMessage[0]->SubscriptionId;
    $request2->SubscriptionIds = $subs_ids;
    $request2->ConnectionTimeout = 10;
    $response2 = $client->GetStreamingEvents($request2);
```
**response:**
```

Fatal error: Uncaught SoapFault exception: [Client] looks like we got  no XML document in C:\wamp64\www\php-ews\src\Client.php:1631 Stack trace: #0 C:\wamp64\www\php-ews\src\Client.php(1631):  SoapClient->__call('GetStreamingEve...', Array) #1 C:\wamp64\www\php-ews\src\Client.php(1631):  jamesiarmes\PhpNtlm\SoapClient->GetStreamingEvents(Object(jamesiarmes\PhpEws\Request\GetStreamingEventsType)) #2 C:\wamp64\www\php-ews\src\Client.php(1112):  jamesiarmes\PhpEws\Client->makeRequest('GetStreamingEve...',  Object(jamesiarmes\PhpEws\Request\GetStreamingEventsType)) #3 C:\wamp64\www\php-ews\examples\event\subs.php(59):  jamesiarmes\PhpEws\Client->GetStreamingEvents(Object(jamesiarmes\PhpEws\Request\GetStreamingEventsType)) #4 {main}   thrown in C:\wamp64\www\php-ews\src\Client.php on line 1631
--



```
Please help
Thanks

**Comment by ZaeemFarooqui** [comment]
I dumped response that was generated by the library and one given by Microsoft as an example for GetStreamingEventsResponse.
**From php-ews Library:** 
```
<Envelope
	xmlns="http://schemas.xmlsoap.org/soap/envelope/">
	<soap11:Header
		xmlns:soap11="http://schemas.xmlsoap.org/soap/envelope/">
		<ServerVersionInfo
			xmlns:xsd="http://www.w3.org/2001/XMLSchema"
			xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" MajorVersion="15" MinorVersion="0" MajorBuildNumber="847" MinorBuildNumber="31" Version="V2_8"
			xmlns="http://schemas.microsoft.com/exchange/services/2006/types" />
		</soap11:Header>
		<soap11:Body
			xmlns:soap11="http://schemas.xmlsoap.org/soap/envelope/">
			<m:GetStreamingEventsResponse
				xmlns:xsd="http://www.w3.org/2001/XMLSchema"
				xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
				xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"
				xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages">
				<m:ResponseMessages>
					<m:GetStreamingEventsResponseMessage ResponseClass="Success">
						<m:ResponseCode>NoError</m:ResponseCode>
						<m:ConnectionStatus>OK</m:ConnectionStatus>
					</m:GetStreamingEventsResponseMessage>
				</m:ResponseMessages>
			</m:GetStreamingEventsResponse>
		</soap11:Body>
	</Envelope>
	<Envelope
		xmlns="http://schemas.xmlsoap.org/soap/envelope/">
		<soap11:Header
			xmlns:soap11="http://schemas.xmlsoap.org/soap/envelope/">
			<ServerVersionInfo
				xmlns:xsd="http://www.w3.org/2001/XMLSchema"
				xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" MajorVersion="15" MinorVersion="0" MajorBuildNumber="847" MinorBuildNumber="31" Version="V2_8"
				xmlns="http://schemas.microsoft.com/exchange/services/2006/types" />
			</soap11:Header>
			<soap11:Body
				xmlns:soap11="http://schemas.xmlsoap.org/soap/envelope/">
				<m:GetStreamingEventsResponse
					xmlns:xsd="http://www.w3.org/2001/XMLSchema"
					xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
					xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"
					xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages">
					<m:ResponseMessages>
						<m:GetStreamingEventsResponseMessage ResponseClass="Success">
							<m:ResponseCode>NoError</m:ResponseCode>
							<m:ConnectionStatus>OK</m:ConnectionStatus>
						</m:GetStreamingEventsResponseMessage>
					</m:ResponseMessages>
				</m:GetStreamingEventsResponse>
			</soap11:Body>
		</Envelope>
		<Envelope
			xmlns="http://schemas.xmlsoap.org/soap/envelope/">
			<soap11:Header
				xmlns:soap11="http://schemas.xmlsoap.org/soap/envelope/">
				<ServerVersionInfo
					xmlns:xsd="http://www.w3.org/2001/XMLSchema"
					xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" MajorVersion="15" MinorVersion="0" MajorBuildNumber="847" MinorBuildNumber="31" Version="V2_8"
					xmlns="http://schemas.microsoft.com/exchange/services/2006/types" />
				</soap11:Header>
				<soap11:Body
					xmlns:soap11="http://schemas.xmlsoap.org/soap/envelope/">
					<m:GetStreamingEventsResponse
						xmlns:xsd="http://www.w3.org/2001/XMLSchema"
						xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
						xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"
						xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages">
						<m:ResponseMessages>
							<m:GetStreamingEventsResponseMessage ResponseClass="Success">
								<m:ResponseCode>NoError</m:ResponseCode>
								<m:ConnectionStatus>Closed</m:ConnectionStatus>
							</m:GetStreamingEventsResponseMessage>
						</m:ResponseMessages>
					</m:GetStreamingEventsResponse>
				</soap11:Body>
			</Envelope>

```

**From Microsoft example:**
```
<?xml version="1.0" encoding="utf-8"?>
<s:Envelope
	xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
	<s:Header>
		<h:ServerVersionInfo MajorVersion="15"
                         MinorVersion="0"
                         MajorBuildNumber="785"
                         MinorBuildNumber="6"
                         Version="V2_6"
			xmlns:h="http://schemas.microsoft.com/exchange/services/2006/types"
			xmlns="http://schemas.microsoft.com/exchange/services/2006/types"
			xmlns:xsd="http://www.w3.org/2001/XMLSchema"
			xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"/>
		</s:Header>
		<soap:Body
			xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
			<m:GetStreamingEventsResponse
				xmlns:xsd="http://www.w3.org/2001/XMLSchema"
				xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
				xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"
				xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages">
				<m:ResponseMessages>
					<m:GetStreamingEventsResponseMessage ResponseClass="Success">
						<m:ResponseCode>NoError</m:ResponseCode>
						<m:Notifications>
							<m:Notification>
								<t:SubscriptionId>JgBibjFwcjAzbWIyMDIubmFtcHJkMDMucHJvZC5vdXRsb29rLmNvbRAAAADwXxVesOnHS5BxUHKwAW88SHjwd1iB0Ag=</t:SubscriptionId>
								<t:CreatedEvent>
									<t:TimeStamp>2013-09-16T04:31:29Z</t:TimeStamp>
									<t:ItemId Id="AAMkADkzNjJjODUzLWZhMDMtNDVkMS05ZDdjLWVmMDlkYjQ1Zjc4MwBGAAAAAABSSWVKrmGUTJE+MVIvofglBwDZGACZQpSgSpyNkexYe2b7AAAAAAENAADZGACZQpSgSpyNkexYe2b7AAANGFYwAAA=" ChangeKey="CQAAAA==" />
									<t:ParentFolderId Id="AQMkADkzNjJjODUzLWZhMDMtNDVkMS05ZDdjLWVmMDlkYjQ1Zjc4MwAuAAADUkllSq5hlEyRPjFSL6H4JQEA2RgAmUKUoEqcjZHsWHtm+wAAAgENAAAA" ChangeKey="AQAAAA==" />
								</t:CreatedEvent>
								<t:NewMailEvent>
									<t:TimeStamp>2013-09-16T04:31:29Z</t:TimeStamp>
									<t:ItemId Id="AAMkADkzNjJjODUzLWZhMDMtNDVkMS05ZDdjLWVmMDlkYjQ1Zjc4MwBGAAAAAABSSWVKrmGUTJE+MVIvofglBwDZGACZQpSgSpyNkexYe2b7AAAAAAENAADZGACZQpSgSpyNkexYe2b7AAANGFYwAAA=" ChangeKey="CQAAAA==" />
									<t:ParentFolderId Id="AQMkADkzNjJjODUzLWZhMDMtNDVkMS05ZDdjLWVmMDlkYjQ1Zjc4MwAuAAADUkllSq5hlEyRPjFSL6H4JQEA2RgAmUKUoEqcjZHsWHtm+wAAAgENAAAA" ChangeKey="AQAAAA==" />
								</t:NewMailEvent>
								<t:ModifiedEvent>
									<t:TimeStamp>2013-09-16T04:31:29Z</t:TimeStamp>
									<t:FolderId Id="AQMkADkzNjJjODUzLWZhMDMtNDVkMS05ZDdjLWVmMDlkYjQ1Zjc4MwAuAAADUkllSq5hlEyRPjFSL6H4JQEA2RgAmUKUoEqcjZHsWHtm+wAAAgENAAAA" ChangeKey="AQAAAA==" />
									<t:ParentFolderId Id="AQMkADkzNjJjODUzLWZhMDMtNDVkMS05ZDdjLWVmMDlkYjQ1Zjc4MwAuAAADUkllSq5hlEyRPjFSL6H4JQEA2RgAmUKUoEqcjZHsWHtm+wAAAgEJAAAA" ChangeKey="AQAAAA==" />
									<t:UnreadCount>1</t:UnreadCount>
								</t:ModifiedEvent>
							</m:Notification>
						</m:Notifications>
					</m:GetStreamingEventsResponseMessage>
				</m:ResponseMessages>
			</m:GetStreamingEventsResponse>
		</soap:Body>
```
xml validator gives and error for the file generated by php-ews library

> The markup in the document following the root element must be well-formed.

**Comment by cpskoshel** [comment]
Получилось решить проблему?
