### ISSUE TITLE
Sorting throws error

### ISSUE THREAD

**Issue by wx007** [jamesiarmes/php-ews#456]
Version): 1.0.0-rc.2
PHP version: 7.1.2

Microsoft Exchange version: Office 365 (outlook.office365.com)

Description of problem:

Trying to add sort ordering to email messages in inbox.
Cannot find any new example code so I'm reusing working code chunk from 2014's php-ews.
This code runs fine until last line is encountered below.
Any help resolving this error would be greatly appreciated.

Thanks

```
// SET SORT ORDER
$request->SortOrder  = new NonEmptyArrayOfFieldOrdersType();
$request->SortOrder->FieldOrder = array();
$order = new FieldOrderType();
$order->FieldURI = UnindexedFieldURIType::ITEM_DATE_TIME_RECEIVED; 
$order->Order = ConversationNodeSortOrder::DATE_ORDER_ASC; 
$request->SortOrder->FieldOrder[] = $order;
```

Example response:

```
PHP Fatal error:  Uncaught SoapFault exception: [a:ErrorInvalidRequest] The request is invalid. in /htdocs/o365_test/src/Client.php:1631
Stack trace:
#0 /htdocs/o365_test/src/Client.php(1631): SoapClient->__call('FindItem', Array)
#1 /htdocs/o365_test/src/Client.php(670): jamesiarmes\PhpEws\Client->makeRequest('FindItem', Object(jamesiarmes\PhpEws\Request\FindItemType))
#2 /htdocs/o365_test/ReadMail_TEST.php(90): jamesiarmes\PhpEws\Client->FindItem(Object(jamesiarmes\PhpEws\Request\FindItemType))
#3 {main}
  thrown in /htdocs/o365_test/src/Client.php on line 1631

Fatal error: Uncaught SoapFault exception: [a:ErrorInvalidRequest] The request is invalid. in /htdocs/o365_test/src/Client.php:1631
Stack trace:
#0 /htdocs/o365_test/src/Client.php(1631): SoapClient->__call('FindItem', Array)
#1 /htdocs/o365_test/src/Client.php(670): jamesiarmes\PhpEws\Client->makeRequest('FindItem', Object(jamesiarmes\PhpEws\Request\FindItemType))
#2 /htdocs/o365_test/ReadMail_TEST.php(90): jamesiarmes\PhpEws\Client->FindItem(Object(jamesiarmes\PhpEws\Request\FindItemType))
#3 {main}
  thrown in /htdocs/o365_test/src/Client.php on line 1631
```
Additional details:

**Comment by jamesiarmes** [comment]
You have two issues with your request:

* `$order->FieldURI` should be an instance of `\jamesiarmes\PhpEws\Type\PathToUnindexedFieldType`.
* `$order->Order` should be a value from `\jamesiarmes\PhpEws\Enumeration\SortDirectionType`.

For example:

```php
// Set sort order.
$order = new FieldOrderType();
$order->FieldURI = new PathToUnindexedFieldType();
$order->FieldURI->FieldURI = UnindexedFieldURIType::ITEM_DATE_TIME_RECEIVED;
$order->Order = SortDirectionType::ASCENDING;
$request->SortOrder = new NonEmptyArrayOfFieldOrdersType();
$request->SortOrder->FieldOrder[] = $order;
```
