### ISSUE TITLE
Error 500 On Exchange 2016

### ISSUE THREAD

**Issue by narkumas** [jamesiarmes/php-ews#475]
Version ## 1.0.0 - 2017-10-03
PHP version: 5.6.0
Microsoft Exchange version: 2016

Description of problem:
My script reads calendars and woirked with Excahnge 2010. Now I have Exchange 2016 and following error is throwed:

Fatal error: Uncaught exception 'Exception' with message 'SOAP client returned status of 500.' in C:\inetpub\wwwroot\intra\vendor\php-ews\php-ews\src\Client.php:1650 Stack trace: #0 C:\inetpub\wwwroot\intra\vendor\php-ews\php-ews\src\Client.php(1633): jamesiarmes\PhpEws\Client->processResponse(NULL) #1 C:\inetpub\wwwroot\intra\vendor\php-ews\php-ews\src\Client.php(670): jamesiarmes\PhpEws\Client->makeRequest('FindItem', Object(jamesiarmes\PhpEws\Request\FindItemType)) #2 C:\inetpub\wwwroot\intra\cal.php(47): jamesiarmes\PhpEws\Client->FindItem(Object(jamesiarmes\PhpEws\Request\FindItemType)) #3 C:\inetpub\wwwroot\intra\kalender.php(197): get_cal('marius.narkus@s...', '10', 0) #4 {main} thrown in C:\inetpub\wwwroot\intra\vendor\php-ews\php-ews\src\Client.php on line 1650

My code:
    ...
    $host = 'verysecret.com';
    $username = 's_exchange_kalender@verysecret.com';
    $password = 'veryverysecret';
    echo $offset;
    $version = Client::VERSION_2016;

    $client = new Client($host, $username, $password, $version);
    $heute=mktime('0','0','00', date('m'), date('d'), date('Y'));
    $startTime = date("Y-m-d\TH:i:s\Z",mktime('0','0','00', date('m'), date('d')+$offset, date('Y')));
    $endTime = date("Y-m-d\TH:i:s\Z", mktime('0','0','00', date("m"), date("d")+$tage+$offset, date("Y")));
    // Build the request.
    $request = new FindItemType();
    $request->Traversal=  jamesiarmes\PhpEws\Enumeration\ItemQueryTraversalType::SHALLOW;
    $request->ItemShape->BaseShape ="AllProperties"; 

    $request->ParentFolderIds = new NonEmptyArrayOfBaseFolderIdsType();
    $request->ContactsView = new ContactsViewType();

    // Find contacts in the contacts folder.
    $folder_id = new DistinguishedFolderIdType();
    $folder_id->Id = DistinguishedFolderIdNameType::CALENDAR;
    $folder_id->Mailbox->EmailAddress=$mailadresse;
    
    $request->CalendarView->StartDate=$startTime;
    $request->CalendarView->EndDate=$endTime;
    $request->ParentFolderIds->DistinguishedFolderId[] = $folder_id;
    //$request->ParentFolderIds->FolderId[]=$folder_id;
    $response = $client->FindItem($request);  **Error comes here**
...

**Comment by narkumas** [comment]
Okay, it is solved. I just had to wait some time after switching to Exchange 2016... Works fine!
