### ISSUE TITLE
how can i delete task..?

### ISSUE THREAD

**Issue by vginfotech** [jamesiarmes/php-ews#484]
Version (e.g. 1.0, dev-master):
PHP version:
Microsoft Exchange version:

Description of problem:
when i try to delete my ews- exchange task following exception thrown. 

Example request:

```php
$client = new Client($host, $username, $password, $version);
$client->setCurlOptions(array(CURLOPT_SSL_VERIFYPEER => false));
$request = new DeleteItemType();
$request->AffectedTaskOccurrences = AffectedTaskOccurrencesType::SPECIFIED;
$request->ItemIds->ItemId = new ItemIdType();
$request->ItemIds->ItemId->Id= $_GET['delete'];
$response = $client->DeleteItem($request);
print_r($response);
```

Example response:

```
<b>Fatal error</b>:  Uncaught SoapFault exception: [a:ErrorSchemaValidation] The request failed schema validation: The required attribute 'DeleteType' is missing. in C:\xampp\htdocs\sync\src\Client.php:1631
Stack trace:
#0 C:\xampp\htdocs\sync\src\Client.php(1631): SoapClient-&gt;__call('DeleteItem', Array)
#1 C:\xampp\htdocs\sync\src\Client.php(1631): jamesiarmes\PhpNtlm\SoapClient-&gt;DeleteItem(Object(jamesiarmes\PhpEws\Request\DeleteItemType))
#2 C:\xampp\htdocs\sync\src\Client.php(547): jamesiarmes\PhpEws\Client-&gt;makeRequest('DeleteItem', Object(jamesiarmes\PhpEws\Request\DeleteItemType))
#3 C:\xampp\htdocs\sync\task_exc.php(66): jamesiarmes\PhpEws\Client-&gt;DeleteItem(Object(jamesiarmes\PhpEws\Request\DeleteItemType))
#4 {main}

```

Additional details:

**Comment by vginfotech** [comment]
Finally i got find solution.

$version = Client::VERSION_2010_SP2;

$client = new Client($host, $username, $password, $version);
$client->setCurlOptions(array(CURLOPT_SSL_VERIFYPEER => false));

$request = new DeleteItemType();
$request->AffectedTaskOccurrences = AffectedTaskOccurrencesType::ALL;
$request->DeleteType = DisposalType::HARD_DELETE;

$request->ItemIds->ItemId = new ItemIdType();
$request->ItemIds->ItemId->Id= $_GET['delete'];

$response = $client->DeleteItem($request);
