### ISSUE TITLE
Update task not working 

### ISSUE THREAD

**Issue by vginfotech** [jamesiarmes/php-ews#485]
Version (e.g. 1.0, dev-master):
PHP version:
Microsoft Exchange version:

Description of problem:
update task not working

Example request:

```php
$event_updates1 =  array(
    array(
        'id' =>$id1,
        'change_key' => $change_key,
        'start' => new DateTime($start),
        'end' => new DateTime($end),
		'description' => $description,
		'subject' => $title,
		'importance' => "Normal",
		'status' => $status
    )
);


$host = $token[0]['ews_host'];
	$username = $token[0]['ews_email'];
	$password = $token[0]['ews_password'];
	$version = Client::VERSION_2010_SP2;

	$client = new Client($host, $username, $password, $version);
	
// Build the request.
$request = new UpdateItemType();
$request->ConflictResolution = ConflictResolutionType::ALWAYS_OVERWRITE;
$request->SendMeetingInvitationsOrCancellations = CalendarItemUpdateOperationType::SEND_TO_ALL_AND_SAVE_COPY;

// Iterate over the updated to be applied, adding each to the request.
foreach ($event_updates1 as $updates) {
    // Build out item change request.
    $change = new ItemChangeType();
    $change->ItemId = new ItemIdType();
    $change->ItemId->Id = $updates['id'];
    $change->ItemId->ChangeKey = $updates['change_key'];
    $change->Updates = new NonEmptyArrayOfItemChangeDescriptionsType();

    
		$field = new SetItemFieldType();
		$field->FieldURI = new PathToUnindexedFieldType();
		$field->FieldURI->FieldURI = UnindexedFieldURIType::TASK_START_DATE;
		$field->CalendarItem = new CalendarItemType();
		$field->CalendarItem->StartDate = $updates['start'];//->format('c');
		$change->Updates->SetItemField[] = $field;
	
	
		// Set the updated end time.
		$field = new SetItemFieldType();
		$field->FieldURI = new PathToUnindexedFieldType();
		$field->FieldURI->FieldURI = UnindexedFieldURIType::TASK_DUE_DATE;
		$field->CalendarItem = new CalendarItemType();
		$field->CalendarItem->DueDate = $updates['end'];//->format('c');
		$change->Updates->SetItemField[] = $field;
	
	
		$field = new SetItemFieldType();
		$field->FieldURI = new PathToUnindexedFieldType();
		$field->FieldURI->FieldURI = UnindexedFieldURIType::ITEM_SUBJECT;
		$field->CalendarItem = new CalendarItemType();
		$field->CalendarItem->Subject = $updates['subject'];
		$change->Updates->SetItemField[] = $field;
		//print_r($field);
	
	//Calendar status Update
		$field = new SetItemFieldType();
		$field->FieldURI = new PathToUnindexedFieldType();
		$field->FieldURI->FieldURI = UnindexedFieldURIType::TASK_STATUS;
		$field->CalendarItem = new CalendarItemType();
		$field->CalendarItem->Status = $update['status'];
		$change->Updates->SetItemField[] = $field;
		//print_r($field);
	
	
	//is all day event..
		$field = new SetItemFieldType();
		$field->FieldURI = new PathToUnindexedFieldType();
		$field->FieldURI->FieldURI = UnindexedFieldURIType::ITEM_IMPORTANCE;
		$field->CalendarItem = new CalendarItemType();
		$field->CalendarItem->Importance = $update['importance'];
		$change->Updates->SetItemField[] = $field;
	

		$change->Updates->SetItemField[] = $field;
	

    $request->ItemChanges[] = $change;
}

$response = $client->UpdateItem($request);

$response_messages = $response->ResponseMessages->UpdateItemResponseMessage;
return $response_messages;

```

Example response:

```
<b>Fatal error</b>:  Uncaught SoapFault exception: [a:ErrorSchemaValidation] The request failed schema validation: The 'id' attribute is not declared. in C:\xampp\htdocs\sync\src\Client.php:1631
Stack trace:
#0 C:\xampp\htdocs\sync\src\Client.php(1631): SoapClient-&gt;__call('UpdateItem', Array)
#1 C:\xampp\htdocs\sync\src\Client.php(1631): jamesiarmes\PhpNtlm\SoapClient-&gt;UpdateItem(Object(jamesiarmes\PhpEws\Request\UpdateItemType))
#2 C:\xampp\htdocs\sync\src\Client.php(1567): jamesiarmes\PhpEws\Client-&gt;makeRequest('UpdateItem', Object(jamesiarmes\PhpEws\Request\UpdateItemType))
#3 C:\xampp\htdocs\sync\include\functions_exc.inc.php(503): jamesiarmes\PhpEws\Client-&gt;UpdateItem(Object(jamesiarmes\PhpEws\Request\UpdateItemType))
#4 C:\xampp\htdocs\sync\task_create_exc.php(26): exchange-&gt;edit_Task('test subject up...', '2018-01-16', '2018-01-18', 'abc', 'AAMkAGM3MTAwM2I...', 'EwAAABYAAADfKRG...', 'inProgress')
#5 {main}
  thrown in <b>C:\xampp\htdocs\sync\src\Client.php</b> on line <b>1631</b><br />

```

Additional details:
when i try to update  task following exception thrown please help me to fix

**Comment by vginfotech** [comment]
Okay, i just got it... 

$client = new Client($host, $username, $password, $version);

$request = new UpdateItemType();
$request->ConflictResolution = ConflictResolutionType::ALWAYS_OVERWRITE;


// Iterate over the updated to be applied, adding each to the request.
foreach ($event_updates_task as $update) {
    // Build out item change request.
    $change = new ItemChangeType();
    $change->ItemId = new ItemIdType();
    $change->ItemId->Id = $update['id'];
    $change->ItemId->ChangeKey = $update['change_key'];
    $change->Updates = new NonEmptyArrayOfItemChangeDescriptionsType();

    // Set the updated start time.
    $field = new SetItemFieldType();
    $field->FieldURI = new PathToUnindexedFieldType();
    $field->FieldURI->FieldURI = UnindexedFieldURIType::TASK_START_DATE;
	$field->Task = new TaskType();
    $field->Task->StartDate = $update['start']->format('c');
    $change->Updates->SetItemField[] = $field;

    // Set the updated end time.
    $field = new SetItemFieldType();
    $field->FieldURI = new PathToUnindexedFieldType();
    $field->FieldURI->FieldURI = UnindexedFieldURIType::TASK_DUE_DATE;
    $field->Task = new TaskType();
    $field->Task->DueDate = $update['end']->format('c');
    $change->Updates->SetItemField[] = $field;
	
	$field = new SetItemFieldType();
	$field->FieldURI = new PathToUnindexedFieldType();
	$field->FieldURI->FieldURI = UnindexedFieldURIType::ITEM_SUBJECT;
	$field->Task = new TaskType();
	$field->Task->Subject = $update['subject'];
	$change->Updates->SetItemField[] = $field;
	
	$field = new SetItemFieldType();
	$field->FieldURI = new PathToUnindexedFieldType();
	$field->FieldURI->FieldURI = new UnindexedFieldURIType();
	$field->FieldURI->FieldURI->_ = UnindexedFieldURIType::ITEM_BODY;

	$field->Task = new TaskType();
	$field->Task->Body = new BodyType();
	$field->Task->Body->_ =$update['description'];
	$field->Task->Body->BodyType = new BodyTypeType();;
	$field->Task->Body->BodyType->_ = BodyTypeType::TEXT;
	$change->Updates->SetItemField[] = $field;

	

    $request->ItemChanges[] = $change;
}

$response = $client->UpdateItem($request);

$response_messages = $response->ResponseMessages->UpdateItemResponseMessage;
return $response_messages;
